### ISSUE TITLE
Allow renaming of secrets

### ISSUE THREAD

**Issue by justinsteffy** [RealGeeks/kustomize-kvsource-vault#1]
Working on the runner for pulley and I've run into the issue where I need to rename secrets. Pulley connects to two databases (`rope` and `mlsraw`), both of which are in vault with names like `host`, `username`, etc...

**Comment by larslevie** [comment]
The current implementation of the of Kustomize secret generator plugin takes a Vault path and a name and returns the resulting secret value tied to that name.

```yaml
secretGenerator:
  - name: domainator-secret
    kvSources:
      - name: vault
        pluginType: go
        args:
          - secret/data/stg/mcp_api//api_key
```

Results in a Kube secret like: 

```yaml
apiVersion: v1
data:
  api_key: XXXXXXXXX
kind: Secret
metadata:
  name: domainator-secret-bc4tbffgg4
  namespace: cms
type: Opaque
```

What about adding a third segment to each arg which would be prepended as a namespace for the secret.

```
secret/data/stg/mcp_api//api_key//some_arbitrary-string
```

Would create the following key in the Kube Secret:

```
some_arbitrary-string/api_key
```
